### PR TITLE
WIP - Run extractor

### PR DESCRIPTION
**Pull request by ryanarbow**

### CODE REVIEW

**Comment by ryanarbow** [comment]
@dmsurti 

Regarding next steps, the next major steps seems to be now how to use the ProfileExtractor and DV Extractor.

I've started this new pull request, but wanted to "talk" through my thinking so you might be able to point me in the right direction...

Order of next steps:
-     Use ProfileExtractor within views.py to extract user profile from url
-     Add extracted data to db for user - based on the models created for the User
-     Display extracted data on analysis_page

My main question is that in the Blog assignment, we went from creating models, adding data (via seed), to displaying them (views.py). Since we aren't seeding the db, do I instead run the extractor in views.py and then add them to the db?

Also, based on the extractor2.py design, when should the DVExtractor be triggered?

**Comment by dmsurti** [comment]
>>  Since we aren't seeding the db, do I instead run the extractor in views.py and then add them to the db?

Yes, that is right. You could also run the code in a python script and populate the db if you want. But so far we don't have a direct view page for a profile; so not sure if seeding is going to help.

**Comment by dmsurti** [comment]
>> Also, based on the extractor2.py design, when should the DVExtractor be triggered?

There are multiple ways to do this. In `capstone/__init__.py`, you can import the DVExtractor and run it as such:

```
from . import extractor2

DV_EXTRACTOR = extractor2.DV_EXTRACTOR()
```

Then where you want to access this DV_EXTRACTOR you can:

```
import blog # OR from blog import DV_EXTRACTOR

user_url = "https://dogvacay.com/best-care-in-the-west-end-dog-boarding-242304?default_service=boarding"
pr_ext = ProfileExtractor(user_url)
user_data = pr_ext.data_for_profile(blog.DV_EXTRACTOR)
```

**Comment by ryanarbow** [comment]
@dmsurti - Instead of "import blog" or "blog.DV_EXTRACTOR", I should be using "capstone", correct? 

However, if I do "import capstone" in my views.py folder I receive an error that ProfileExtractor is undefined. Do I need to import extractor2 here as well? I tried that and don't see the error.

**Comment by ryanarbow** [comment]
@dmsurti  - Quick question, am I correct in creating a profile_analysis.etc.etc.... for each variable? Ex. 
    profile_analysis.price_min = (user_data.loc['fee_min'])
    profile_analysis.price_mean = (user_data.loc['fee_mean']) 
    profile_analysis.price_max = (user_data.loc['fee_max'])

**Comment by dmsurti** [comment]
>> Instead of "import blog" or "blog.DV_EXTRACTOR", I should be using "capstone", correct?

Yes, that is correct.

>> However, if I do "import capstone" in my views.py folder I receive an error that ProfileExtractor is undefined. Do I need to import extractor2 here as well? I tried that and don't see the error.

No, we are only making a single instance of `DVExtractor` in `__init__.py`. So to import `ProfileExtractor` in `views.py`, you need to do: `from extractor2 import ProfileExtractor`.

**Comment by dmsurti** [comment]
>> Quick question, am I correct in creating a profile_analysis.etc.etc.... for each variable? Ex.
profile_analysis.price_min = (user_data.loc['fee_min'])

Yes, that is the right way to do it.

**Comment by ryanarbow** [comment]
@dmsurti updated the code; however, receive a 400 error when I submit the url on the landing page. Do you mind reviewing?

**Comment by dmsurti** [comment]
@ryanarbow  Can you please submit the error trace?

**Comment by ryanarbow** [comment]
@dmsurti - what is the error trace? I see..
Webpage:
400 Bad Request
The browser (or proxy) sent a request that this server could not understand.

In terminal:
10.240.1.20 - - [02/Jan/2017 01:15:11] "POST / HTTP/1.1" 400 -

**Comment by dmsurti** [comment]
>> what is the error trace?

Usually a trace printed on the console, which contains the call stack...

>> 400 Bad Request

Check your app routes? Are you sure the URL/app route for the given request is handled in your code. 

I think this may be the cause: https://github.com/ryanarbow/capstone/blob/master/capstone/templates/landing_page.html#L53

Here you are not setting the name of the input element. Try:

`<input type="text" id="text" name="url" placeholder="Input your url">`, because you are doing `url = request.form['url']` in your code. The input element's name attribute should be the same as the `form[?]` attribute.

**Pull request merged**
